name: CI

on:
  push:
  pull_request:

jobs:
  flatpak:
    name: "Flatpak CI"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: [Resolve, ResolveStudio]
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - name: Free Disk Space
      uses: endersonmenezes/free-disk-space@v2
      with:
        remove_android: true
        remove_dotnet: true
        remove_haskell: true
        remove_tool_cache: true
        remove_swap: true
        remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
        remove_packages_one_command: true
        remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
        testing: false
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: com.blackmagic.${{ matrix.file }}
        manifest-path: com.blackmagic.${{ matrix.file }}.yaml
        cache-key: flatpak-builder-${{ matrix.file }}-${{ github.sha }}
