name: CI

on:
  push:
  pull_request:

jobs:
  flatpak:
    name: "Flatpak CI"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: [Resolve, ResolveStudio]
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: com.blackmagic.${{ matrix.file }}
        manifest-path: com.blackmagic.${{ matrix.file }}.yaml
        cache-key: flatpak-builder-${{ matrix.file }}-${{ github.sha }}
